# Generated by Django 4.0.5 on 2022-07-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_video_alter_post_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='DbLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('work_place', models.CharField(max_length=100)),
            ],
        ),
    ]
